<a href="https://colab.research.google.com/github/suryadarma240306-hue/Tugas-Statistika-Surya-2B/blob/main/STATISTIKA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import scipy.stats as stats
Movie = pd.read_csv('/content/drive/MyDrive/MovieData-2018-2020.csv')
Movie.head(30)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
2,Deadpool 2,R,Action,2018,"May 18, 2018 (United States)",7.7,505000.0,David Leitch,Rhett Reese,Ryan Reynolds,Canada,110000000.0,7.864705e+08,Twentieth Century Fox,119.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0
5,Hereditary,R,Drama,2018,"June 8, 2018 (United States)",7.3,259000.0,Ari Aster,Ari Aster,Toni Collette,United States,10000000.0,8.023966e+07,PalmStar Media,127.0
6,A Simple Favor,R,Comedy,2018,"September 14, 2018 (United States)",6.8,136000.0,Paul Feig,Darcey Bell,Anna Kendrick,Canada,20000000.0,9.764462e+07,BRON Studios,117.0
7,Aquaman,PG-13,Action,2018,"December 21, 2018 (United States)",6.9,404000.0,James Wan,David Leslie Johnson-McGoldrick,Jason Momoa,United States,160000000.0,1.148486e+09,Warner Bros.,143.0
8,Ready Player One,PG-13,Action,2018,"March 29, 2018 (United States)",7.4,388000.0,Steven Spielberg,Zak Penn,Tye Sheridan,United States,175000000.0,5.828937e+08,Warner Bros.,140.0
9,Spider-Man: Into the Spider-Verse,PG,Animation,2018,"December 14, 2018 (United States)",8.4,411000.0,Bob Persichetti,Phil Lord,Shameik Moore,United States,90000000.0,3.755408e+08,Sony Pictures Entertainment (SPE),117.0
10,Mission: Impossible - Fallout,PG-13,Action,2018,"July 27, 2018 (United States)",7.7,303000.0,Christopher McQuarrie,Bruce Geller,Tom Cruise,United States,178000000.0,7.916574e+08,Paramount Pictures,147.0
11,Venom,PG-13,Action,2018,"October 5, 2018 (United States)",6.7,387000.0,Ruben Fleischer,Jeff Pinkner,Tom Hardy,China,100000000.0,8.560852e+08,Avi Arad Productions,112.0
12,Green Book,PG-13,Biography,2018,"November 16, 2018 (United States)",8.2,414000.0,Peter Farrelly,Nick Vallelonga,Viggo Mortensen,United States,23000000.0,3.217527e+08,Participant,130.0
13,Crazy Rich Asians,PG-13,Comedy,2018,"August 15, 2018 (United States)",6.9,152000.0,Jon M. Chu,Peter Chiarelli,Constance Wu,United States,30000000.0,2.385392e+08,Warner Bros.,120.0
14,Ant-Man and the Wasp,PG-13,Action,2018,"July 6, 2018 (United States)",7.0,333000.0,Peyton Reed,Chris McKenna,Paul Rudd,United States,162000000.0,6.226741e+08,Marvel Studios,118.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,9.341371e+07,Focus Features,135.0
16,The Predator,R,Action,2018,"September 14, 2018 (United States)",5.3,120000.0,Shane Black,Fred Dekker,Boyd Holbrook,United States,88000000.0,1.605421e+08,Twentieth Century Fox,107.0
17,White Boy Rick,R,Crime,2018,"September 14, 2018 (United States)",6.5,33000.0,Yann Demange,Andy Weiss,Matthew McConaughey,United States,29000000.0,2.595748e+07,LBI Productions,111.0
18,Solo: A Star Wars Story,PG-13,Action,2018,"May 25, 2018 (United States)",6.9,306000.0,Ron Howard,Jonathan Kasdan,Alden Ehrenreich,United States,275000000.0,3.929248e+08,Lucasfilm,135.0
19,Midnight Sun,PG-13,Drama,2018,"March 23, 2018 (United States)",6.6,26000.0,Scott Speer,Kenji Bando,Bella Thorne,United States,2800000.0,2.736547e+07,Boies / Schiller Film Group,91.0
20,Under the Silver Lake,R,Crime,2018,"April 19, 2019 (United States)",6.5,36000.0,David Robert Mitchell,David Robert Mitchell,Andrew Garfield,United States,8500000.0,2.053469e+06,Vendian Entertainment,139.0
21,Den of Thieves,R,Action,2018,"January 19, 2018 (United States)",7.0,99000.0,Christian Gudegast,Christian Gudegast,Gerard Butler,United States,30000000.0,8.050962e+07,STX Films,140.0
22,Annihilation,R,Adventure,2018,"February 23, 2018 (United States)",6.8,292000.0,Alex Garland,Alex Garland,Natalie Portman,United Kingdom,40000000.0,4.307092e+07,Paramount Pictures,115.0
23,Red Sparrow,R,Action,2018,"March 2, 2018 (United States)",6.6,173000.0,Francis Lawrence,Justin Haythe,Jennifer Lawrence,United States,69000000.0,1.515726e+08,Chernin Entertainment,140.0
24,A Star Is Born,R,Drama,2018,"October 5, 2018 (United States)",7.6,350000.0,Bradley Cooper,Eric Roth,Lady Gaga,United States,36000000.0,4.361889e+08,Warner Bros. Pictures,136.0
25,Mamma Mia! Here We Go Again,PG-13,Comedy,2018,"July 20, 2018 (United States)",6.6,85000.0,Ol Parker,Ol Parker,Lily James,United Kingdom,75000000.0,3.956182e+08,Universal Pictures,114.0
26,Death Wish,R,Action,2018,"March 2, 2018 (United States)",6.3,67000.0,Eli Roth,Joe Carnahan,Bruce Willis,United States,30000000.0,4.956271e+07,Cave 76,107.0
27,Instant Family,PG-13,Comedy,2018,"November 16, 2018 (United States)",7.3,97000.0,Sean Anders,Sean Anders,Mark Wahlberg,United States,48000000.0,1.205562e+08,Closest to the Hole Productions,118.0
28,Jurassic World: Fallen Kingdom,PG-13,Action,2018,"June 22, 2018 (United States)",6.2,277000.0,J.A. Bayona,Derek Connolly,Chris Pratt,United States,170000000.0,1.310466e+09,Universal Pictures,128.0
29,Eighth Grade,R,Comedy,2018,"August 3, 2018 (United States)",7.4,68000.0,Bo Burnham,Bo Burnham,Elsie Fisher,United States,2000000.0,1.434743e+07,A24,93.0

BERDASARKAN GENRE

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Mengimpor dataset film IMDB dari file CSV
ImdbMovie_df = pd.read_csv('/content/drive/MyDrive/MovieData-2018-2020.csv')

# Menghilangkan data yang tidak memiliki nilai pada kolom 'genre'
# Nilai kosong pada kolom genre dapat menyebabkan proses stratify gagal
ImdbMovie_df = ImdbMovie_df.dropna(subset=['genre'])

# Menyeleksi genre yang memiliki jumlah data minimal 2
# Hal ini dilakukan agar setiap genre masih dapat dibagi saat proses stratified sampling
genre_counts = ImdbMovie_df['genre'].value_counts()
valid_genres = genre_counts[genre_counts >= 2].index
ImdbMovie_df = ImdbMovie_df[ImdbMovie_df['genre'].isin(valid_genres)]
# -------------------------------------

# 2. Membagi data dengan teknik Stratified Sampling
_, stratified_sample = train_test_split(
    ImdbMovie_df,
    test_size=0.3,                     # Menentukan ukuran sampel sebesar 30% dari total data
    stratify=ImdbMovie_df['genre'],    # Menjaga proporsi genre agar tetap seimbang dalam sampel
    random_state=63                    # Mengatur nilai acak berdasarkan NIM agar hasil tetap konsisten
)

# 3. Mengambil 30 baris pertama dari data hasil sampling
sample_30_teratas = stratified_sample.head(30)

# 4. Menampilkan hasil 30 data teratas dari stratified sampling
print("Stratified Sampling (30 Data Teratas):")
display(sample_30_teratas)

Stratified Sampling (30 Data Teratas):

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
117,Assassination Nation,R,Action,2018,"September 21, 2018 (United States)",6.0,17000.0,Sam Levinson,Sam Levinson,Odessa Young,United States,7000000.0,2.584988e+06,BRON Studios,108.0
214,What Men Want,R,Comedy,2019,"February 8, 2019 (United States)",5.3,26000.0,Adam Shankman,Tina Gordon,Taraji P. Henson,United States,20000000.0,7.221629e+07,BET Films,117.0
265,The Call of the Wild,PG,Adventure,2020,"February 21, 2020 (United States)",6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,Canada,135000000.0,1.111055e+08,20th Century Studios,100.0
47,Bad Times at the El Royale,R,Crime,2018,"October 12, 2018 (United States)",7.1,135000.0,Drew Goddard,Drew Goddard,Jeff Bridges,United States,32000000.0,3.188272e+07,Goddard Textiles,141.0
177,The Lion King,PG,Animation,2019,"July 19, 2019 (United States)",6.9,222000.0,Jon Favreau,Jeff Nathanson,Donald Glover,United States,260000000.0,1.670728e+09,Walt Disney Pictures,118.0
241,The Fanatic,R,Crime,2019,"August 30, 2019 (Mexico)",4.1,7900.0,Fred Durst,Fred Durst,John Travolta,United States,18000000.0,NaN,Daniel Grodnik Productions,88.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
189,Frozen II,PG,Animation,2019,"November 22, 2019 (United States)",6.8,148000.0,Chris Buck,Jennifer Lee,Kristen Bell,United States,150000000.0,1.450027e+09,Walt Disney Animation Studios,103.0
207,Maleficent: Mistress of Evil,PG,Adventure,2019,"October 18, 2019 (United States)",6.6,91000.0,Joachim Rønning,Linda Woolverton,Angelina Jolie,United States,185000000.0,4.917301e+08,Walt Disney Pictures,119.0
28,Jurassic World: Fallen Kingdom,PG-13,Action,2018,"June 22, 2018 (United States)",6.2,277000.0,J.A. Bayona,Derek Connolly,Chris Pratt,United States,170000000.0,1.310466e+09,Universal Pictures,128.0
249,Little,PG-13,Comedy,2019,"April 12, 2019 (United States)",5.5,12000.0,Tina Gordon,Tracy Oliver,Regina Hall,United States,20000000.0,4.900067e+07,Universal Pictures,109.0
248,Poms,PG-13,Comedy,2019,"May 10, 2019 (United States)",6.0,4700.0,Zara Hayes,Zara Hayes,Diane Keaton,United Kingdom,10000000.0,1.641822e+07,Entertainment One,90.0
231,Ip Man 4: The Finale,Not Rated,Action,2019,"December 20, 2019 (China)",7.0,27000.0,Wilson Yip,Edmond Wong,Donnie Yen,Hong Kong,52000000.0,1.763460e+08,Golden Harvest Company,107.0
14,Ant-Man and the Wasp,PG-13,Action,2018,"July 6, 2018 (United States)",7.0,333000.0,Peyton Reed,Chris McKenna,Paul Rudd,United States,162000000.0,6.226741e+08,Marvel Studios,118.0
136,SuperFly,R,Action,2018,"June 13, 2018 (United States)",5.2,6500.0,Director X.,Alex Tse,Trevor Jackson,United States,16000000.0,2.078068e+07,Columbia Pictures,116.0
153,Knives Out,PG-13,Comedy,2019,"November 27, 2019 (United States)",7.9,505000.0,Rian Johnson,Rian Johnson,Daniel Craig,United States,40000000.0,3.115394e+08,Lionsgate,130.0
160,It Chapter Two,R,Drama,2019,"September 6, 2019 (United States)",6.5,222000.0,Andy Muschietti,Stephen King,Jessica Chastain,United States,79000000.0,4.730932e+08,New Line Cinema,169.0
25,Mamma Mia! Here We Go Again,PG-13,Comedy,2018,"July 20, 2018 (United States)",6.6,85000.0,Ol Parker,Ol Parker,Lily James,United Kingdom,75000000.0,3.956182e+08,Universal Pictures,114.0
171,Downton Abbey,PG,Drama,2019,"September 20, 2019 (United States)",7.4,43000.0,Michael Engler,Julian Fellowes,Stephen Campbell Moore,United Kingdom,13000000.0,2.378600e+08,Carnival Film & Television,122.0
23,Red Sparrow,R,Action,2018,"March 2, 2018 (United States)",6.6,173000.0,Francis Lawrence,Justin Haythe,Jennifer Lawrence,United States,69000000.0,1.515726e+08,Chernin Entertainment,140.0
61,Peter Rabbit,PG,Animation,2018,"February 9, 2018 (United States)",6.6,38000.0,Will Gluck,Rob Lieber,James Corden,United States,50000000.0,3.514961e+08,Columbia Pictures,95.0
250,The Prodigy,R,Fantasy,2019,"February 8, 2019 (United States)",5.9,24000.0,Nicholas McCarthy,Jeff Buhler,Taylor Schilling,United States,6000000.0,2.115026e+07,Orion Pictures,92.0
235,Don't Let Go,R,Drama,2019,"August 30, 2019 (United States)",6.4,8000.0,Jacob Estes,Jacob Estes,David Oyelowo,United States,5000000.0,5.288011e+06,Blumhouse Productions,103.0
69,The Girl in the Spider's Web,R,Action,2018,"November 9, 2018 (United States)",6.1,44000.0,Fede Alvarez,David Lagercrantz,Claire Foy,Germany,43000000.0,3.516492e+07,Columbia Pictures,115.0
208,The Secret Life of Pets 2,PG,Animation,2019,"June 7, 2019 (United States)",6.5,55000.0,Chris Renaud,Brian Lynch,Patton Oswalt,United States,80000000.0,4.300513e+08,Universal Pictures,86.0
270,The Robinsons,NaN,Action,2020,"November 10, 2020 (United States)",NaN,NaN,Directors,Aleks Alifirenko Jr.,Billy Hartmann,United States,10000.0,NaN,NaN,90.0
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
11,Venom,PG-13,Action,2018,"October 5, 2018 (United States)",6.7,387000.0,Ruben Fleischer,Jeff Pinkner,Tom Hardy,China,100000000.0,8.560852e+08,Avi Arad Productions,112.0
50,The Mule,R,Crime,2018,"December 14, 2018 (United States)",7.0,121000.0,Clint Eastwood,Nick Schenk,Clint Eastwood,United States,50000000.0,1.748044e+08,Warner Bros.,116.0
179,Marriage Story,R,Comedy,2019,"December 6, 2019 (United States)",7.9,265000.0,Noah Baumbach,Noah Baumbach,Adam Driver,United Kingdom,18600000.0,3.336860e+05,Heyday Films,137.0

In [27]:
sample_30_teratas.describe()

,year,score,votes,budget,gross,runtime
count,30.000000,29.000000,29.000000,3.000000e+01,2.800000e+01,30.000000
mean,2018.633333,6.568966,161106.896552,7.345367e+07,4.238821e+08,114.066667
std,0.614948,0.881194,201234.601773,8.018722e+07,5.514860e+08,19.791906
min,2018.000000,4.100000,4700.000000,1.000000e+04,3.336860e+05,86.000000
25%,2018.000000,6.100000,26000.000000,1.725000e+07,3.434437e+07,100.750000
50%,2019.000000,6.600000,85000.000000,4.650000e+07,2.071030e+08,114.500000
75%,2019.000000,7.000000,222000.000000,9.500000e+07,4.777524e+08,121.250000
max,2020.000000,8.400000,897000.000000,3.210000e+08,2.048360e+09,169.000000

MENGHITUNG ESTIMASI BUDGET

In [28]:
import scipy.stats as stats
import math

# 1. Mengambil data budget dari hasil 30 sampel pertama
# Periksa kembali agar nama kolom 'budget' sudah sama dengan yang ada pada dataset
data_budget = sample_30_teratas['budget']

# 2. Menghitung nilai statistik utama berdasarkan data sampel
x_bar = data_budget.mean()         # Menentukan nilai rata-rata budget dari sampel
s = data_budget.std(ddof=1)        # Menentukan standar deviasi sampel dengan derajat bebas n-1
n = len(data_budget)               # Menentukan banyaknya data yang digunakan dalam sampel
confidence_level = 0.95            # Menetapkan tingkat kepercayaan sebesar 95%

# 3. Menentukan nilai alpha, derajat bebas, standard error, t kritis, dan margin error
alpha = (1 - confidence_level)
df = n - 1
standard_error = s / math.sqrt(n)
critical_t = stats.t.ppf(1 - alpha/2, df)
margin_of_error = critical_t * standard_error

# 4. Menghitung batas bawah dan batas atas interval kepercayaan
lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

# 5. Menampilkan hasil perhitungan statistik dan confidence interval
print("=== STATISTIK SAMPEL ===")
print("Jumlah Sampel (n)     : ", n)
print("Rata-rata Sampel (x̄)  : {:.2f}".format(x_bar))
print("Standar Deviasi (s)   : {:.2f}".format(s))
print("-" * 30)
print("=== HASIL T-DISTRIBUSI ===")
print("Critical t-value      : {:.2f}".format(critical_t))
print("Margin of error       : {:.2f}".format(margin_of_error))
print("Confidence Interval   : ({:.2f}, {:.2f})".format(lower_bound, upper_bound))
print("The {:.1%} confidence interval for the population mean budget is:".format(confidence_level))
print("Between {:.2f} and {:.2f}".format(lower_bound, upper_bound))

=== STATISTIK SAMPEL ===
Jumlah Sampel (n)     :  30
Rata-rata Sampel (x̄)  : 73453666.67
Standar Deviasi (s)   : 80187221.81
------------------------------
=== HASIL T-DISTRIBUSI ===
Critical t-value      : 2.05
Margin of error       : 29942400.71
Confidence Interval   : (43511265.95, 103396067.38)
The 95.0% confidence interval for the population mean budget is:
Between 43511265.95 and 103396067.38